# Problem
# Running ESLint: Create a workflow that runs the ESLint tool on your codebase
#  to check for linting errors. You can use the checkout action to clone your repository,
#   the setup-node action to install Node.js and the eslint package, and the run command
#   to execute the eslint command.

# Approach :
# name: Run ESLint on: push jobs: eslint: runs-on: ubuntu-latest steps:
#  - name: Checkout code uses: actions/checkout@v2 - name: Install Node.js
#  uses: actions/setup-node@v2 with: node-version: '14.x' - name: Install
#  dependencies run: npm install - name: Run ESLint run: npx eslint .

name: Run ESLint
on: push
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: INstall Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install
        run: npm install
      - name: Run eslint
        run: npx eslint
